# Generated by Django 4.2.3 on 2023-07-20 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('nome_item', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('preco_venda', models.CharField(max_length=15)),
                ('valor_venda', models.CharField(blank=True, max_length=15, null=True)),
                ('situacao', models.CharField(default='PENDENTE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('sku', models.CharField(max_length=100)),
                ('nome_item', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=15)),
                ('quantidade', models.IntegerField()),
                ('data_vencimento', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_unitario', models.CharField(blank=True, max_length=15)),
                ('preco_pago', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('nome_item', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=15)),
                ('quantidade', models.IntegerField()),
                ('valor_vendido', models.CharField(max_length=15)),
                ('valor_lote', models.CharField(max_length=15)),
                ('situacao', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ALIMENTOS', 'ALIMENTOS'), ('BEBIDAS', 'BEBIDAS'), ('CONSUMIVEIS', 'CONSUMIVEIS')], max_length=15)),
                ('valor_unitario', models.CharField(max_length=15)),
                ('imagem', models.CharField(default='image/padrao.png', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('sku', models.CharField(max_length=100)),
                ('nome_item', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('preco_venda', models.CharField(max_length=15)),
                ('valor_venda', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trasacoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_anterior', models.CharField(max_length=15)),
                ('saldo_atual', models.CharField(max_length=15)),
                ('acao', models.CharField(choices=[('VENDA', 'VENDA'), ('COMPRA', 'COMPRA'), ('TROCO', 'TROCO'), ('DEPOSITO', 'DEPOSITO'), ('SAQUE', 'SAQUE')], max_length=20)),
                ('data_hora', models.DateTimeField()),
            ],
        ),
    ]
