# Generated by Django 4.2.3 on 2023-07-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
        migrations.DeleteModel(
            name='Trasacoe',
        ),
    ]
